platform :ios, '7.0'

pod 'AFNetworking', '~> 2.6.1'
pod 'CocoaAsyncSocket', '~> 7.4.2'
pod 'Reachability', '~> 3.2'
pod 'IQKeyboardManager', '~> 3.3.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'FMDB', '~> 2.5'
pod 'JDStatusBarNotification', '~> 1.5.2'
pod 'UMengAnalyticsSDK', '~> 3.6.5'
pod 'UMengSocial', '~> 4.2.3'
pod 'iOS-WechatSDK', '~> 1.6.1'
pod 'ActionSheetPicker-3.0', '~> 2.0.3'
pod 'CustomBadge', '~> 3.0.0'
pod 'VRGCalendarView', '~> 0.0.1'
pod 'WPAttributedMarkup', '~> 1.0.0'
pod 'ZYQAssetPickerController', '~> 1.0.0'
pod 'OpenUDID', '~> 1.0.0'
pod 'BaiduMapKit', '~> 2.10.2'
